class Nasu:
    nasu_points_1 = "Nasu: Reach 10 Points"
    nasu_points_2 = "Nasu: Reach 40 Points"
    nasu_points_3 = "Nasu: Reach 160 Points"
    nasu_points_4 = "Nasu: Reach 640 Points"
    nasu_points_5 = "Nasu: Reach 2560 Points"
    nasu_points_6 = "Nasu: Reach 5000 Points"

class AoOni:
    floor_1_key = "Ao Oni: Floor 1 Room Key"
    floor_1_mansion_key = "Ao Oni: Floor 1 Mansion Key"
    floor_1_monoko = "Ao Oni: Floor 1 Save Monoko"
    floor_1_poniko = "Ao Oni: Floor 1 Save Poniko"
    floor_1_monoe = "Ao Oni: Floor 1 Save Monoe"
    floor_1_bonus_1 = "Ao Oni: Floor 1 Bonus 1"
    floor_1_bonus_2 = "Ao Oni: Floor 1 Bonus 2"
    floor_1_bonus_3 = "Ao Oni: Floor 1 Bonus 3"
    floor_2_key = "Ao Oni: Floor 2 Room Key"
    floor_2_mansion_key = "Ao Oni: Floor 2 Mansion Key"
    floor_2_monoko = "Ao Oni: Floor 2 Save Monoko"
    floor_2_poniko = "Ao Oni: Floor 2 Save Poniko"
    floor_2_monoe = "Ao Oni: Floor 2 Save Monoe"
    floor_2_bonus_1 = "Ao Oni: Floor 2 Bonus 1"
    floor_2_bonus_2 = "Ao Oni: Floor 2 Bonus 2"
    floor_2_bonus_3 = "Ao Oni: Floor 2 Bonus 3"
    floor_3_key = "Ao Oni: Floor 3 Room Key"
    floor_3_mansion_key = "Ao Oni: Floor 3 Mansion Key"
    floor_3_monoko = "Ao Oni: Floor 3 Save Monoko"
    floor_3_poniko = "Ao Oni: Floor 3 Save Poniko"
    floor_3_monoe = "Ao Oni: Floor 3 Save Monoe"
    floor_3_bonus_1 = "Ao Oni: Floor 3 Bonus 1"
    floor_3_bonus_2 = "Ao Oni: Floor 3 Bonus 2"
    floor_3_bonus_3 = "Ao Oni: Floor 3 Bonus 3"
    floor_4_key = "Ao Oni: Floor 4 Room Key"
    floor_4_mansion_key = "Ao Oni: Floor 4 Mansion Key"
    floor_4_monoko = "Ao Oni: Floor 4 Save Monoko"
    floor_4_poniko = "Ao Oni: Floor 4 Save Poniko"
    floor_4_monoe = "Ao Oni: Floor 4 Save Monoe"
    floor_4_bonus_1 = "Ao Oni: Floor 4 Bonus 1"
    floor_4_bonus_2 = "Ao Oni: Floor 4 Bonus 2"
    floor_4_bonus_3 = "Ao Oni: Floor 4 Bonus 3"
    floor_5_key = "Ao Oni: Floor 5 Room Key"
    floor_5_mansion_key = "Ao Oni: Floor 5 Mansion Key"
    floor_5_monoko = "Ao Oni: Floor 5 Save Monoko"
    floor_5_poniko = "Ao Oni: Floor 5 Save Poniko"
    floor_5_monoe = "Ao Oni: Floor 5 Save Monoe"
    floor_5_bonus_1 = "Ao Oni: Floor 5 Bonus 1"
    floor_5_bonus_2 = "Ao Oni: Floor 5 Bonus 2"
    floor_5_bonus_3 = "Ao Oni: Floor 5 Bonus 3"

class WitchAdventure:
    boss_1 = "Witch Adventure: Boss 1 Defeated"
    boss_2 = "Witch Adventure: Boss 2 Defeated"
    boss_3 = "Witch Adventure: Boss 3 Defeated"
    boss_4 = "Witch Adventure: Boss 4 Defeated"
    boss_5 = "Witch Adventure: Boss 5 Defeated"

class RealBedroom:
    nasu = "Bedroom: Item in Famicom"

class Streets:
    diary_1 = "Streets: Shrine"
    diary_2 = "Streets: Dark Ground at Chase"
    diary_3 = "Streets: Ground at Chase"
    knife = "Streets: Weapon Stuck in Pork"
    diary_secret = "Streets: Hidden Butcher's Prize"
    egg = "Streets: Onsen-san's End"
    diary_monoko_1 = "Bed Maze: Underneath one Bed of Many"
    diary_monoko_2 = "Bed Maze: Bed Middle Dead End"
    diary_monoko_3 = "Bed Maze: Bed Top Dead End"
    jellyfish = "Streets: Jellyfish Behind Start"

class Wilderness:
    red_eye = "Wilderness: Corpse of an Eye Plant"
    diary_toriningen = "Wilderness: Near Picnic"
    death_glyph = "Wilderness: In Eye at Temple Base"
    diary_train = "Train: Empty Train Seat"
    diary_town_box = "Wilderness: Town Boxes"
    war_glyph = "Wilderness: House Glyph"
    kite = "Mural Forest: Item Stuck in Tree"
    kalimba = "Train: Red Eye Creature's Tune"
    diary_piori = "Wilderness: Death of a Green Piori"
    sun_glyph = "Wilderness: Piori Trade"
    moon_glyph = "Mural Forest: Bug Creature's Song"
    diary_endless = "Wilderness: Pool in Endless Wilderness"
    umbrella = "Sky Garden: Forgotten Near Bench"
    diary_bench = "Sky Garden: Under Bench"
    diary_lookout = "Sky Garden: Hidden Near Lookout"
    egg = "Sky Garden: Picked Flower"
    jellyfish = "Wilderness: Jellyfish Living Amongst the Piori"

class Docks:
    planks = "Docks: Dead End Boards"
    hamsa = "Docks: Boarded Dead End"
    boarded_art = "Docks: Hidden Boarded Item"
    yen_1 = "Docks: Loose Item Near Train"
    yen_2 = "Docks: Loose Item Past Boarded Dead End"
    yen_3 = "Docks: Loose Item Near Fisherman"
    yen_4 = "Docks: Trash Can"
    yen_5 = "Docks: Under Movable Crate"
    yen_6 = "Docks: Toriningen's Dropped Purse"
    yen_7 = "Docks: Guarded Lower Pier Near Scale"
    yen_8 = "Docks: Upper of Two Tiered Pier"
    yen_9 = "Docks: Lower of Two Tiered Pier"
    yen_10 = "Docks: Middle of Toriningen Trap"
    blood_bag = "Docks: Vending Machine Purchase"
    sad_fish = "Docks: Fisherman's Catch"
    diary_strober = "Docks: Strober's Fallen Gift"
    diary_forest_tree = "Docks: Obscured by Tree"
    dirty_game_cartridge = "Docks: Cursed Mansion Outskirts"
    diary_pink_sea = "Docks: Pink Sea Puddle"
    egg = "Docks: Poniko's Secret"
    mask_of_fear = "Hell: Uboa's Gift"
    jellyfish = "Docks: Jellyfish Alone Before Fisherman"

class Mall:
    hidden_storage = "Mall: Hidden Item on Shelf"
    flute = "Mall: O Man's Magic Trick"
    eman_song = "Mall: E Man's Beat"
    diary_flute = "Mall: O Man's Gift"
    diary_plant = "Mall: Obscured by Tree at Top of Mall"
    valve = "Mall: Shelf Item in Storage Upper Floor"
    diary_boxes = "Mall: Hiding Amongst the Boxes"
    egg = "Mall: Sleep Amongst the Mannequins"
    rooftop_key = "Mall: Deep Within Dark Room Above Boxes Left"
    diary_upper_boxes = "Mall: Deep Within Dark Room Above Boxes Right"
    mysterious_cartridge = "Mall: Roof Cat"
    jellyfish = "Mall: Jellyfish Atop the Mall"

class School:
    picture_1 = "School: Resting in Locker"
    diary_bathroom = "School: Atop Urinal"
    books = "School: Second Floor Shelf"
    brush = "School: Pirori Trade"
    triangle = "School: Walking Eye Trade"
    diary_triangle = "School Walking Eye's Gift"
    picture_2 = "School: Fleebie Trade"
    picture_3 = "School: Top of Window"
    picture_4 = "School: Resting on Cabinet"
    lever = "School Storm: Dark Room Rubble"
    toilet_key = "School Storm: Hidden on Desk in Plain Sight"
    lantern = "School Storm: Light Amongst Floating Ground"
    diary_cabinet = "School Storm: Near Cabinet Madotsuki"
    diary_switch = "School Storm: Dead End Switch"
    diary_zipper = "School Storm: Hidden In Grate Before Sewer"
    egg = "School Storm: Crying Before KyuuKyuu"
    diary_kyuukyuu = "School Storm: Before Door to FACE"
    jellyfish = "School: Jellyfish Locked in Third Floor Bathroom"

class Blocks:
    girl_1 = "Blocks: Find Girl (First)"
    girl_2 = "Blocks: Find Girl (Second)"
    girl_3 = "Blocks: Find Girl (Third)"
    girl_4 = "Blocks: Find Girl (Fourth)"
    girl_5 = "Blocks: Find Girl (Fifth)"
    girl_6 = "Blocks: Find Girl (Sixth)"
    diary_blocks = "Blocks: Secret Through Speedy Block"

class Snow:
    hat_and_scarf = "Snow: Meet Mafurako 1"
    egg = "Snow: Meet Mafurako 2"
    diary_snowman = "Snow: Snowman Madotsuki"

class Sewer:
    diary_pool = "Sewer: Obscured by Deep Water in Pool Room"
    jellyfish = "Sewer: Jellyfish Guarded by Red Eyes"

class Apartment:
    diary_lone_bed = "Apartment: Under Bed in Empty Room"
    diary_open_box = "Apartment: In Box"
    rusty_key = "Apartment: On Desk in Locked Room"
    diary_outside = "Apartment: On Left Side of Roof"
