class DreamRegions:
    menu = "Menu"
    real_bedroom = "Real Bedroom"
    nasu_game = "Nasu Game"
    ao_oni_game = "Ao Oni Game"
    witch_game = "Witch Adventure Game"
    dream_bedroom = "Dream Bedroom"
    nexus = "Nexus"

    ao_oni_2 = "Ao Oni Level 2"
    ao_oni_3 = "Ao Oni Level 3"
    ao_oni_4 = "Ao Oni Level 4"
    ao_oni_5 = "Ao Oni Level 5"

    initial_street = "Initial Street Part"
    streets = "Dimly Lit Streets"
    butcher_front = "Butcher Front Door"
    butcher_feeding = "Butcher Feeding Room"
    road = "Rainy Road"
    bed_maze = "Monoe's Bed Maze"

    temple_base = "Wilderness Temple Base"
    train_1 = "Train Path 1"
    wilderness_town = "Wilderness Town"
    wilderness_town_interior = "Wilderness Town Interiors"
    train_2 = "Train Path 2"
    wilderness_night = "Wilderness Mural Forest"
    train_3 = "Train Path 3"
    train_4 = "Train Path 4"
    endless_wilderness = "Endless Wilderness"
    sky_garden = "Sky Garden"

    school_front = "School Front"
    school_first = "School First Floor"
    school_book_room = "School Book Room"
    school_second = "School Second Floor"
    school_band_room = "School Band Room"
    school_third = 'School Third Floor'
    school_locked_bathroom = "School Locked Bathroom"
    school_third_class = "School Third Floor Classroom"
    school_roof = "School Roof"
    school_outside_storm = "School Roof (Storm)"
    school_storm_interior_front = "School Storm Interior (Front)"
    school_storm_interior_front_past_switch = "School Storm Inteior Past Switch (Front)"
    school_storm_interior_back = "School Storm Interior (Back)"

    mall = "Mall Entrance"
    music_room = "Mall Music Room"
    storage_room = "Mall Storage Room"
    storage_room_upper = "Mall Storage Room Upper"
    mannequin_room = "Mall Mannequin Room"
    box_room = "Mall Box Room"
    mall_roof = "Mall Roof"

    dock_fisher = "Fishing Dock"
    dock_w_room = "Dock W Room"
    dock_vending = "Dock Vending Machine"
    docks_crate = "Dock Crate Room"
    docks_scale = "Dock Scale Room"
    dock_train = "Dock Train Station"
    docks_two_story = "Dock Two Story Pier"
    docks_lighthouse = "Dock Lighthouse Path"
    igloo = "Igloo"
    pink_sea = "Pink Sea"
    poniko_room = "Poniko's Room"

    sewers = "Sewers"
    blocks = "Blocks World"
    snow = "Snow World"

    apartment_bottom_floor = "Apartment Bottom Floor"
    apartment_top_floor = "Apartment Top Floor"
    apartment_roof = "Apartment Roof"
    apartment_ufo = "Masada's Ship"

    normal_end = "Normal Ending"
    secret_end = "Secret Ending"



class DreamEntrances:
    begin_day = "Begin Day"
    sleep = "Go to Bed"
    nasu_game_path = "Play Nasu in Real Life"
    ao_oni_game_path = "Play Ao Oni in Dream"
    witch_game_path = "Play Witch Adventure in Dream"
    leave_dream_room = "Leave Dream Room"

    ao_oni_1_to_2 = "Beat Level 1 of Ao Oni"
    ao_oni_2_to_3 = "Beat Level 2 of Ao Oni"
    ao_oni_3_to_4 = "Beat Level 3 of Ao Oni"
    ao_oni_4_to_5 = "Beat Level 4 of Ao Oni"
    ao_oni_5_to_6 = "Beat Level 5 of Ao Oni"

    nexus_to_streets = "Streets Door"
    nexus_to_wilderness = "Wilderness Door"
    nexus_to_docks = "Docks Door"
    nexus_to_mall = "Mall Door"
    nexus_to_school = "School Door"
    nexus_to_sewers = "Sewer Door"
    nexus_to_apartment = "Apartment Door"

    initial_streets_to_streets = "Walk Streets to Dreamy Section"
    streets_to_butcher_front = "Butcher Shop Front Door"
    butcher_front_to_butcher_back = "Butcher Shop Feeding Room Door"
    butcher_feeding_to_road = "Door to Dark Road"
    streets_to_sewers = "Manhole Lid"
    sewers_to_streets = "Climb Up to Manhole Lid"
    road_to_monoe = "Path to Monoe"

    hamsa_path = "Secret Path to Endless"
    first_train = "Take the First Train"
    first_train_off = "Get off the First Train"
    second_train = "Take the Second Train"
    second_train_off = "Get off the Second Train"
    third_train = "Take the Third Train"
    third_train_off = "Get off the Third Train"
    third_train_to_fourth = "Third Train to Fourth"
    fourth_train = "Take the Fourth Train"
    fourth_train_off = "Get off the Fourth Train"
    wilderness_town_to_sewers = "Wilderness Town Well"
    sewers_to_wilderness_town = "Climb Up to Wilderness Town"
    train_to_docks = "Train Headed for Docks"
    docks_to_train = "Train Headed for Wilderness Temple"
    wilderness_homes_doors = "Open Wilderness Town Doors"
    temple_base_to_garden = "Climb Temple Stairs"

    mall_to_storage = "Go into Mall Storage"
    storage_to_upper_storage = "Go Up in Mall Elevator"
    enter_mannequin_room = "Enter Mannequin Room"
    enter_box_room = "Enter Box Room"
    upper_storage_to_roof = "Use Roof Exit"
    storage_to_sewers = "Open Mall Sewer Lid"
    sewers_to_storage = "Climb Ladder to Mall Storage"
    mall_to_music = "Enter Music Room"

    fisher_to_w = "Fisher to W Room"
    w_to_vending = "W to Vending Machine"
    vending_to_crate = "Vending Machine to Crate Room"
    crate_to_scale = "Crate Room to Scale Room"
    scale_to_two_story = "Scale Room to Two Story Pier"
    two_story_to_train = "Two Story Pier to Train Stop"
    dock_train_to_lighthouse = "Train Stop to Lighthouse Path"
    lighthouse_to_igloo = "Enter Igloo From Forest"
    igloo_to_pink_sea = "Jump Into Igloo Hole"
    pink_sea_to_poniko = "Enter Poniko's Room"

    school_front_to_first = "Enter School"
    school_first_to_book = "Enter Book Classroom"
    school_first_to_second = "Climb to School Second Floor"
    school_second_to_music = "Enter Music Classroom"
    school_second_to_third = "Climb to School Third Floor"
    school_third_to_class = "Enter Top Classrooms"
    school_third_to_bathroom = "Enter Locked Bathroom"
    school_third_to_storm = "Transition to School Storm"
    school_storm_to_front = "Break Through School Window"
    school_storm_front_to_lever = "Flip School Storm Lever"
    school_storm_front_to_back = "Follow Monoe"

    sewers_to_blocks = "Climb up to Block World"
    blocks_to_snow = "Door to Snow World"
    snow_to_igloo = "Snow World Igloo"

    apartment_bottom_to_top = "Take Apartment to Top Floor"
    apartment_top_to_roof = "Take Apartment Roof Exit"
    to_normal_end = "Escape Apartment"
    apartment_roof_to_ufo = "Get Abducted"
    to_secret_end = "Sleep on UFO"
