class JebCabin:
    knife = "Jeb's Cabin: Rocking Chair Item"
    camera = "Jeb's Cabin: Camera Barrel"
    rifle = "Jeb's Cabin: Rifle Near Rocking Chair"
    coffee = "Jeb's Cabin: Coffee"
    ammo = "Jeb's Cabin: Ammo"
    clear = "Jeb's Cabin Cleared"

class TurkeyCreek:
    turkey_call = "Turkey Creek: Turkey Call Item"
    hen_ammo = "Turkey Creek: Hen House Barrel Ammo"
    hen_coffee = "Turkey Creek: Hen House Coffee"
    house_ammo = "Turkey Creek: House Barrel Ammo"
    dark_spot_ammo = "Turkey Creek: Dark Spot Barrel Ammo"
    house_coffee = "Turkey Creek: House Barrel Coffee"
    rock_coffee = "Turkey Creek: Rock Coffee"
    clear = "Turkey Creek Cleared"

class FrigidValley:
    shack_ammo = "Frigid Valley: Barrel Ammo"
    truck = "Frigid Valley: Broken Truck Ammo"
    path_ammo = "Frigid Valley: Early Path Barrel Ammo"
    second_ammo = "Frigid Valley: Second Dead-end Barrel Ammo"
    trailer_coffee = "Frigid Valley: Trailer Coffee"
    trailer_ammo = "Frigid Valley: Trailer Ammo"
    trailer_barrel_ammo = "Frigid Valley: Trailer Barrel Ammo"
    trailer_tv_coffee = "Frigid Valley: Trailer Coffee Near TV"
    final_shack_coffee = "Frigid Valley: Final Shack Barrel Coffee"
    final_shack_ammo = "Frigid Valley: Final Shack Barrel Ammo"
    late_path_ammo = "Frigid Valley: Late Path Barrel Ammo"
    clear = "Frigid Valley Cleared"

class HowlingMarsh:
    revolver = "Howling Marsh: Church Podium Item"
    house_coffee = "Howling Marsh: House Coffee"
    house_ammo = "Howling Marsh: House Upstairs Ammo"
    fence_house_ammo_1 = "Howling Marsh: Fenced House Barrel Ammo 1"
    fence_house_ammo_2 = "Howling Marsh: Fenced House Barrel Ammo 2"
    church_key = "Howling Marsh: Graveyard Key Item"
    graveyard_ammo = "Howling Marsh: Graveyard Barrel Ammo"
    greenhouse_ammo_1 = "Howling Marsh: Greenhouse Barrel Ammo 1"
    greenhouse_ammo_2 = "Howling Marsh: Greenhouse Barrel Ammo 2"
    trailer_coffee = "Howling Marsh: Trailer Coffee"
    clear = "Howling Marsh Cleared"

class BleedingGrove:
    bren = "Bleeding Grove: Starved Corpse's Weapon"
    clear = "Bleeding Grove Cleared"

class JebLore:
    guide = "Jeb's Cabin: Controls Manual"
    cdc = "Jeb's Cabin: Totally Real CDC Notice"
    hero_of_horned_snake = "Turkey Creek: Hero of the Horned Snake"
    ate_fish = "Turkey Creek: They Ate All The Fish! Note"
    starved_chickens = "Turkey Creek: Note on Starved Chickens"
    newfound_god = "Turkey Creek: Newfound God Gibberish"
    the_turkeys = "Turkey Creek: Dead Man's Realization on Turkeys"
    the_uktena_1 = "Frigid Valley: The Uktena Part 1"
    the_uktena_2 = "Frigid Valley: The Uktena Part 2"
    loud_sound = "Frigid Valley: Note on How Loud The Sound Is"
    ringing = "Frigid Valley: Ringing Sound Note"
    nightmare = "Frigid Valley: Nightmare Note"
    church_note = "Howling Marsh: The End Has Come Note"
    trailer_day_1 = "Howling Marsh: Diary Day 1"
    trailer_day_5 = "Howling Marsh: Diary Day 5"
    more_than_one = "Bleeding Grove: More Than One Note"
    the_uktena_3 = "Bleeding Grove: The Uktena Part 3"
    the_hunger = "Bleeding Grove: The Hunger Note"
    no_food = "Bleeding Grove: No Food Left Note"

class CabinCamera:
    squirrel = "Jeb's Cabin: Squirrel Photo"

class TurkeyCamera:
    turkey_1 = "Turkey Creek: Hen House Turkey Photo"
    dark_linked_turkey_1 = "Turkey Creek: Dark Spot Linked Turkey 1 Photo"
    dark_linked_turkey_2 = "Turkey Creek: Dark Spot Linked Turkey 2 Photo"
    dark_linked_turkey_3 = "Turkey Creek: Dark Spot Linked Turkey 3 Photo"
    turkey_2 = "Turkey Creek: Rock Turkey Photo"
    rock_linked_turkey_1 = "Turkey Creek: Rock Linked Turkey 1 Photo"
    rock_linked_turkey_2 = "Turkey Creek: Rock Linked Turkey 2 Photo"
    rock_linked_turkey_3 = "Turkey Creek: Rock Linked Turkey 3 Photo"
    creek_dead_body = "Turkey Creek: Decomposing Body"
    house_linked_turkey_1 = "Turkey Creek: House Linked Turkey 1 Photo"
    house_linked_turkey_2 = "Turkey Creek: House Linked Turkey 2 Photo"
    house_linked_turkey_3 = "Turkey Creek: House Linked Turkey 3 Photo"
    turkey_3 = "Turkey Creek: Barrel Turkey"
    headless_turkey = "Turkey Creek: Headless Turkey"

class FrigidCamera:
    early_wolf_1 = "Frigid Valley: Early Dead-end Wolf 1 Photo"
    early_wolf_2 = "Frigid Valley: Early Dead-end Wolf 2 Photo"
    early_wolf_3 = "Frigid Valley: Early Dead-end Wolf 3 Photo"
    second_wolf_1 = "Frigid Valley: Second Dead-end Wolf 1 Photo"
    second_wolf_2 = "Frigid Valley: Second Dead-end Wolf 2 Photo"
    second_wolf_3 = "Frigid Valley: Second Dead-end Wolf 3 Photo"
    second_wolf_4 = "Frigid Valley: Second Dead-end Wolf 4 Photo"
    open_wolf_1 = "Frigid Valley: Open Area Wolf 1 Photo"
    open_wolf_2 = "Frigid Valley: Open Area Wolf 2 Photo"
    circle_meat = "Frigid Valley: Rock Circle Meat Photo"
    trailer_dog = "Frigid Valley: Trailer Skinned Dog Photo"
    tree_dog_1 = "Frigid Valley: Skinned Dog in Tree 1 Photo"
    tree_dog_2 = "Frigid Valley: Skinned Dog in Tree 2 Photo"
    elk = "Frigid Valley: Huge Elk Photo"
    skinned_return_1 = "Frigid Valley: Skinned Return Dog 1 Photo"
    skinned_return_2 = "Frigid Valley: Skinned Return Dog 2 Photo"
    skinned_return_3 = "Frigid Valley: Skinned Return Dog 3 Photo"
    skinned_return_4 = "Frigid Valley: Skinned Return Dog 4 Photo"
    skinned_return_5 = "Frigid Valley: Skinned Return Dog 5 Photo"
    skinned_return_6 = "Frigid Valley: Skinned Return Dog 6 Photo"
    skinned_return_7 = "Frigid Valley: Skinned Return Dog 7 Photo"
    snowman_skull = "Frigid Valley: Snowman Skull Photo"
    mountain_wolf = "Frigid Valley: Wolf Watching Over Valley Photo"

class HowlingCamera:
    bear_1 = "Howling Marsh: Bear 1 Photo"
    bear_2 = "Howling Marsh: Bear 2 Photo"
    bear_3 = "Howling Marsh: Bear 3 Photo"
    bear_4 = "Howling Marsh: Bear 4 Photo"
    burned_corpses_1 = "Howling Marsh: Burned Corpses 1 Photo"
    burned_corpses_2 = "Howling Marsh: Burned Corpses 2 Photo"
    burned_corpses_3 = "Howling Marsh: Burned Corpses 3 Photo"
    burned_corpses_4 = "Howling Marsh: Burned Corpses 4 Photo"
    burned_corpses_5 = "Howling Marsh: Burned Corpses 5 Photo"
    burned_corpses_6 = "Howling Marsh: Burned Corpses 6 Photo"
    huge_bear = "Howling Marsh: Huge Bear Photo"

class BleedingCamera:
    starved = "Bleeding Grove: Starved Man Photo"

class TheBBQBasket:
    butcher_knives = "The BBQ Basket: Cooking Utensils"
    binoculars = "The BBQ Basket: Binoculars in Barrel"
    ruger = "The BBQ Basket: Ruger in Barrel"
    coffee = "The BBQ Basket: Coffee"
    clear = "The BBQ Basket Cleared"

class RitualRoad:
    bridge_ammo = "Ritual Road: Early Bridge Barrel Ammo"
    outside_venereal_ammo = "Ritual Road: Outside Dollar Venereal Barrel Ammo"
    venereal_coffee = "Ritual Road: Dollar Venereal Coffee"
    venereal_ammo = "Ritual Road: Dollar Venereal Ammo"
    truck_ammo = "Ritual Road: Truck Barrel Ammo"
    tent_coffee = "Ritual Road: Tent Coffee"
    clear = "Ritual Road Cleared"

class LakeLinger:
    starting_ammo = "Lake Linger: Starting House Barrel Ammo"
    boat_house_coffee = "Lake Linger: Boat House Fridge Coffee"
    island_coffee = "Lake Linger: Island Barrel Coffee"
    island_ammo = "Lake Linger: Island Barrel Ammo"
    dead_end_ammo = "Lake Linger: Northern Dead End Barrel Ammo"
    two_story_coffee = "Lake Linger: Two Story Building Barrel Coffee"
    main_office_ammo = "Lake Linger: Main Office Barrel Ammo"
    main_office_trap = "Lake Linger: Main Office Bear Trap Pack"
    north_house_trap = "Lake Linger: North House Set Bear Trap"
    coffee_trap_trap_1 = "Lake Linger: Coffee Trap Set Bear Trap 1"
    coffee_trap_trap_2 = "Lake Linger: Coffee Trap Set Bear Trap 2"
    coffee_trap_trap_3 = "Lake Linger: Coffee Trap Set Bear Trap 3"
    coffee_trap_coffee = "Lake Linger: Coffee Trap Coffee"
    dam_ammo_1 = "Lake Linger: Dam Barrel Ammo 1"
    dam_ammo_2 = "Lake Linger: Dam Barrel Ammo 2"
    trapped_start_trap_1 = "Lake Linger: Trapped Start Trap 1"
    trapped_start_trap_2 = "Lake Linger: Trapped Start Trap 2"
    trapped_start_trap_3 = "Lake Linger: Trapped Start Trap 3"
    trapped_start_trap_4 = "Lake Linger: Trapped Start Trap 4"
    trapped_start_trap_5 = "Lake Linger: Trapped Start Trap 5"
    trapped_start_trap_6 = "Lake Linger: Trapped Start Trap 6"
    trapped_start_trap_7 = "Lake Linger: Trapped Start Trap 7"
    clear = "Lake Linger Cleared"

class PallidPark:
    chamber_ammo = "Pallid Park: Office Chamber Barrel Ammo"
    owner_ammo = "Pallid Park: Dead Owner Bench Ammo"
    swamp_bridge_ammo = "Pallid Park: Swamp Bridge Barrel Ammo"
    crossbow = "Pallid Park: Crossbow Park Bench Item"
    north_coffee = "Pallid Park: North Coffee Barrel Ammo"
    swamp_shack_ammo = "Pallid Park: Swamp Shack Barrel Ammo"
    swamp_shack_bolts = "Pallid Park: Swamp Shack Bolts"
    swamp_shack_coffee = "Pallid Park: Swamp Shack Coffee"
    south_office_coffee = "Pallid Park: South Office Coffee"
    south_office_ammo = "Pallid Park: South Office Ammo"
    clear = "Pallid Park Cleared"

class BurningGrove:
    banjo = "Burning Grove: Jeeb's Banjo"
    clear = "Burning Grove Cleared"

jeb_clears = [JebCabin.clear, TurkeyCreek.clear, FrigidValley.clear, HowlingMarsh.clear, BleedingGrove.clear]
jeeb_clears = [TheBBQBasket.clear, RitualRoad.clear, LakeLinger.clear, PallidPark.clear, BurningGrove.clear]

class JeebLore:
    jeeb_diary = "The BBQ Basket: Jeeb's Diary"
    cia = "The BBQ Basket: The Totally Real CIA Message"
    tree = "The BBQ Basket: Praise the Tree Note"
    nothing_satisfies = "Ritual Road: Nothing Satisfies Note"
    black_spines = "Ritual Road: Black Spines Note"
    taste_that_flesh = "Ritual Road: Taste That Flesh Note"
    elation = "Ritual Road: Elation Note"
    boat_diary = "Lake Linger: Boathouse Diary"
    the_deluge = "Lake Linger: The Deluge"
    almighty_baya = "Lake Linger: Almighty Bayagototh Note"
    otter_warning = "Lake Linger: Otter Warning Note"
    juiced_baby = "Pallid Park: Juiced Baby Note"
    woke_gallows = "Pallid Park: Too Woke Note"
    nipple_yogurt = "Pallid Park: Nipple Yogurt Note"
    great_leech = "Pallid Park: The Great Leech of Tlanusi'yi"
    right_to_be_naked = "Pallid Park: Right to be Naked Note"
    what_magic = "Burning Grove: What Magic Note"
    partook_flesh = "Burning Grove: Partook Flesh Note"
    feel_the_vines = "Burning Grove: Feel The Vines Note"
    someday_peace = "Burning Grove: Someday Peace Note"

class BBQMeat:
    squirrel = "The BBQ Basket: Squirrel Meat"

class RitualMeat:
    bird_bridge_1 = "Ritual Road: Bridge Condor 1 Meat"
    bird_bridge_2 = "Ritual Road: Bridge Condor 2 Meat"
    bird_bridge_3 = "Ritual Road: Bridge Condor 3 Meat"
    roadkill_bridge_1 = "Ritual Road: Roadkill Bridge 1 Meat"
    roadkill_bridge_2 = "Ritual Road: Roadkill Bridge 2 Meat"
    dollar_bird_1 = "Ritual Road: Dollar Venereal Condor 1 Meat"
    dollar_bird_2 = "Ritual Road: Dollar Venereal Condor 2 Meat"
    dollar_bird_3 = "Ritual Road: Dollar Venereal Condor 3 Meat"
    tree_roadkill = "Ritual Road: Tree Roadkill Meat"
    intersection_bird_1 = "Ritual Road: Intersection Condor 1 Meat"
    intersection_bird_2 = "Ritual Road: Intersection Condor 2 Meat"
    intersection_roadkill = "Ritual Road: Intersection Roadkill Meat"
    car_crash = "Ritual Road: Questionable Car Crash Meat"
    legless_deer = "Ritual Road: Legless Deer Meat"
    your_truck = "Ritual Road: Roadkill Under Truck Meat"

class LakeMeat:
    dead_body = "Lake Linger: Dead Person Meat"
    hiding_otter_1 = "Lake Linger: Hiding Otter 1 Meat"
    hiding_otter_2 = "Lake Linger: Hiding Otter 2 Meat"
    hiding_otter_3 = "Lake Linger: Hiding Otter 3 Meat"
    covered_body = "Lake Linger: Covered Body Meat"
    north_house_otter_1 = "Lake Linger: North House Otter 1 Meat"
    north_house_otter_2 = "Lake Linger: North House Otter 2 Meat"
    north_house_otter_3 = "Lake Linger: North House Otter 3 Meat"
    north_house_otter_4 = "Lake Linger: North House Otter 4 Meat"
    north_house_otter_5 = "Lake Linger: North House Otter 5 Meat"
    north_house_otter_6 = "Lake Linger: North House Otter 6 Meat"
    north_house_otter_7 = "Lake Linger: North House Otter 7 Meat"
    coffee_trap_otter_1 = "Lake Linger: Trapped Coffee Otter 1 Meat"
    coffee_trap_otter_2 = "Lake Linger: Trapped Coffee Otter 2 Meat"
    coffee_trap_otter_3 = "Lake Linger: Trapped Coffee Otter 3 Meat"
    dam_otter_1 = "Lake Linger: Dam Water Otter 1 Meat"
    dam_otter_2 = "Lake Linger: Dam Water Otter 2 Meat"
    warning_otter_1 = "Lake Linger: Warning Otter 1 Meat"
    warning_otter_2 = "Lake Linger: Warning Otter 2 Meat"
    warning_otter_3 = "Lake Linger: Warning Otter 3 Meat"
    warning_otter_4 = "Lake Linger: Warning Otter 4 Meat"
    warning_otter_5 = "Lake Linger: Warning Otter 5 Meat"
    huge_fish = "Lake Linger: Huge Fish Meat"
    trapped_start_1 = "Lake Linger: Trapped Start Otter 1 Meat"
    trapped_start_2 = "Lake Linger: Trapped Start Otter 2 Meat"
    trapped_start_3 = "Lake Linger: Trapped Start Otter 3 Meat"
    trapped_start_4 = "Lake Linger: Trapped Start Otter 4 Meat"

class PallidMeat:
    dougie = "Pallid Park: Little Doggy Meat"
    dead_owner = "Pallid Park: Dead Owner Meat"
    north_leech_1 = "Pallid Park: North Leech 1 Meat"
    north_leech_2 = "Pallid Park: North Leech 2 Meat"
    north_leech_3 = "Pallid Park: North Leech 3 Meat"
    north_leech_4 = "Pallid Park: North Leech 4 Meat"
    south_leech_1 = "Pallid Park: South Leech 1 Meat"
    south_leech_2 = "Pallid Park: South Leech 2 Meat"
    south_leech_3 = "Pallid Park: South Leech 3 Meat"
    south_leech_4 = "Pallid Park: South Leech 4 Meat"
    ghost_1 = "Pallid Park: Ghost 1 Meat"
    ghost_2 = "Pallid Park: Ghost 2 Meat"

class BurningMeat:
    burning_dog_1 = "Burning Grove: Burning Dog 1 Meat"
    burning_dog_2 = "Burning Grove: Burning Dog 2 Meat"
    burning_dog_3 = "Burning Grove: Burning Dog 3 Meat"
    burning_dog_4 = "Burning Grove: Burning Dog 4 Meat"
    burning_dog_5 = "Burning Grove: Burning Dog 5 Meat"
    burning_dog_6 = "Burning Grove: Burning Dog 6 Meat"
    rotting_corpse = "Burning Grove: Rotting Corpse Meat"

class Hyena:
    turkey_creek = "Turkey Creek: Hyena Deep in Creek"
    frigid_valley = "Frigid Valley: Hyena Behind Truck in Hills"
    howling_marsh = "Howling Marsh: Hyena Behind Trees"
    lake_linger = "Lake Linger: Hyena Behind Dam Fences"
    burning_grove = "Burning Grove: Hyena In Attic"

    jeb_hyena = [turkey_creek, frigid_valley, howling_marsh]
    jeeb_hyena = [lake_linger, burning_grove]